### ISSUE TITLE
Index out of range on some layout configurations

### ISSUE THREAD

**Issue by stefanomondino** [dPackumar/FlexiCollectionViewLayout#1]
Hi, this layout is really great!
I'm trying to use it in my project, right now I'm using random numbers to determine width and height factors and sometimes I have crashes here with Index out of range on the array:

`localColumnHeightsPerSection[index + shortestNextIndex] = columnHeight + cellHeight + interItemSpacing`

**Comment by stefanomondino** [comment]
would it be that bad to wrap that line around an if statement checking if the index is still in bounds? I've forked and I'm about to try it out, If it seems to work I'll submit a PR.

**Comment by dPackumar** [comment]
I have already fixed this issue, yet to make a release. Will release sometime today or tomorrow.

**Comment by stefanomondino** [comment]
ok, wonderful! Thanks!
